### ISSUE TITLE
Where will the database download 

### ISSUE THREAD

**Issue by laly-zz** [KiritoZ-Z/PhantomCore#1]
Where will the database download?

Thx.

**Comment by Viste** [comment]
Use YTDB for trinity-core ^_~

**Comment by laly-zz** [comment]
Thank you very much

**Comment by Viste** [comment]
http://ytdb.ru/showthread.php?t=5227 you can find it here

**Comment by laly-zz** [comment]
I can not browse the site, the site can not view .

You can not access the specified web page!
Error Type: connect failed

But thank you,  would like to be able to normal tomorrow .

**Comment by Viste** [comment]
http://filebeam.com/5452921d370048313f6f1178cd33418e - full
http://filebeam.com/3b01e78c94d867f6e423be7be0e5486a - update

**Comment by laly-zz** [comment]
Big thank you, but only updates 546 & 547,not full datebase.

**Comment by Viste** [comment]
http://filebeam.com/64b79e650665fc63e7a5163c490ee4cc sorry this is full

**Comment by laly-zz** [comment]
It's right, thank you very much, you are good man .
