### ISSUE TITLE
Deathbringer's Will Normal & Heroic. Воля Смертоносного нормальный и геройческие (Spell ID included, ИД Спелов внутри)

### ISSUE THREAD

**Issue by LOKY** [KiritoZ-Z/PhantomCore#10]
DK: Str, Haste, Crit 71484, 71492, 71491  (HEROIC: 71561, 71560, 71491) 
Druid: Str, Agi, Haste 71484, 71485, 71492  (HEROIC: 71561, 71556, 71560)
Hunter: Agi, Crit, AP 71485, 71491, 71486  (HEROIC: 71556, 71491, 71558)
Paladin: Str, Haste, Crit 71484, 71492, 71491 (HEROIC: 71561, 71560, 71491)
Rogue: Agi, Haste, AP 71485, 71492, 71486  (HEROIC: 71556, 71560, 71558)
Shaman: Agi, AP, Haste 71485, 71486, 71492  (HEROIC: 71556, 71558, 71560)
Warrior: Str, Crit, Haste 71484, 71492, 71491  (HEROIC: 71561, 71491, 71560)

Hidden CD 90sec.
Duration 30 sec.
Прокает спелл рандомно, 3 разных спелла за класс.

**Comment by LOKY** [comment]
Не работает вовсе, это просто данные чтобы вам жизнь облегчить.

**Comment by Viste** [comment]
завтра... послезавтра, как пойдет

**Comment by LOKY** [comment]
Никто не торопит никого =) Благодорю за ответ.

**Comment by gpadmin** [comment]
На ТС вроде выкладывали

**Comment by Viste** [comment]
у меня свой вариант
