### ISSUE TITLE
Обновление карт

### ISSUE THREAD

**Issue by VenT** [KiritoZ-Z/PhantomCore#100]
На данный момент Фантом использует старые карты еще от 3.3.3а. Просьба обновить до последней версии.
Коммит на репо Myh: http://github.com/myh/wow/commit/86fe5b12223e7c0be9a2ae8a4f7c979414356973

**Comment by Null45** [comment]
Мы без вас разберемся, что и когда делать, левые репозитории, которым мы не доверяем не используются.

**Comment by VenT** [comment]
Какие левые репозитории то? Этот же коммит есть и в офф репо. Поискать просто надо. А без обновления карт, будут замечаться глюки с "невидимыми стенами" в игре. Например нельзя пройти в некоторые здания в даларане.
