### ISSUE TITLE
серъезный баг с WPE

### ISSUE THREAD

**Issue by SignFinder** [KiritoZ-Z/PhantomCore#102]
Каким то образом через фильтр wpe вот эти спелы http://ru.wowhead.com/spell=67890   http://ru.wowhead.com/spell=54998   на этих итемах http://ru.wowhead.com/item=8346
http://ru.wowhead.com/item=23825  снимается кд. За 5 секунд можно спел использовать раз 40.

**Comment by Viste** [comment]
это гкд :)

**Comment by SignFinder** [comment]
бу
