### ISSUE TITLE
Dalaran nto flagged as PvP

### ISSUE THREAD

**Issue by GuguRD** [KiritoZ-Z/PhantomCore#107]
Once again I come as a noob asking for help and reporting this hehehe...

Dalaran is still not flagged as Sanctuary zone, I think it can be a DBC issue but not sure.

**Comment by SignFinder** [comment]
delete all maps from worldserver.conf
in line vmap.ignoreMapIds = ""

**Comment by GuguRD** [comment]
vmap.enableLOS = 1
vmap.enableHeight = 1
vmap.ignoreMapIds = ""
vmap.ignoreSpellIds = "7720"
vmap.petLOS = 1
vmap.enableIndoorCheck = 1

and still broken... using enUS DBCs and client

**Comment by GuguRD** [comment]
Solved on lastest revisions.
