### ISSUE TITLE
Glyph of Freezing Trap

### ISSUE THREAD

**Issue by gpadmin** [KiritoZ-Z/PhantomCore#13]
http://github.com/mangos/mangos/commit/cdc849ea3fa2439d48d8d78f0fa4c37ce0ce74cb

**Comment by Viste** [comment]
не критичный баг...

**Comment by gpadmin** [comment]
Я попробую сам написать, подскажите какая функция на ТС = cast_at_remove = true;

**Comment by crAwling** [comment]
## Перенеси с мангоса Хэд, патч аналогичный в функцию HandleAuraSpecificMods, cast_at_remove - не нужно переносить

to Viste, вы когда что-то делаете - думаете? Заменили нормальный патч на deathbringer's will на откровенный гавнокод. Разрабы разрабами, но предложенный вариант был лучше
