### ISSUE TITLE
Понижение длительности прерывающих эффектов

### ISSUE THREAD

**Issue by Koord** [KiritoZ-Z/PhantomCore#14]
Не работают таланты и подобные ауры, понижающие время длительности прерывающих эффектов (например Антимагия)

Например - http://ru.wowhead.com/spell=20256

Нашел на мангосе решение данной проблемы - http://ru-mangos.ru/showthread.php?t=321 . Просьба реализовать это в ФантомКор, так как таланты данного вида очень важны

**Comment by Viste** [comment]
без б :)

**Comment by Koord** [comment]
Спасибо большое за вашу работу! Вы лучшие!
