### ISSUE TITLE
Lst compile errors fix!!

### ISSUE THREAD

**Issue by AwkwardDev** [KiritoZ-Z/PhantomCore#16]
First of all I want to apologize that I write on English since I see its russian core, but I'm Bulgarian and unfortunately I learn Russian only from one year and I yet can't write it perfect. Second I never done a patches and ect, I'm not good with them, but here goes the fix for the HomeMovementGenerator I have found. It should fix the compile, its not yet tested ingame, but soon I will. :)

http://filebeam.com/upload.php

Hope it helps! /cheers for the core, great work guys!!!!!

**Comment by Viste** [comment]
its link on upload file to filebeam not for patch

**Comment by AwkwardDev** [comment]
As I said, I'm not good at making patches :S.

**Comment by Viste** [comment]
This link is not on the patch, but the download page

**Comment by AwkwardDev** [comment]
Oh my god! That was stupid! I just done 4 things at same time and I did a miskate, sorry!

Here is the real download link of the .cpp source - http://filebeam.com/81d29e8d1f43c90425e4f90d975e9feb 

Passowrd is - bluecloud
Once again sorry!
