### ISSUE TITLE
[Талант]Призматический плащ[маг]

### ISSUE THREAD

**Issue by AniRB** [KiritoZ-Z/PhantomCore#17]
При прокачивания таланта 3/3 в невидимость маг не уходит, если 2/3 то уходит

**Comment by KiritoZ-Z** [comment]
пробуем релог и пишем работает после него или нет

**Comment by AniRB** [comment]
не работает

**Comment by AniRB** [comment]
src/game/Spell.cpp
это
                if (duration == 0)
                {
                    m_spellAura->Remove();
                    return SPELL_MISS_IMMUNE;
Заменить на
                if (m_spellInfo->Id != 42783 || m_spellInfo->Id != 32612)
                {
                   if (duration == 0)
                   {
                       m_spellAura->Remove();
                       return SPELL_MISS_IMMUNE;
                   }

**Comment by foxdalas** [comment]
Теперь работает ?

**Comment by AniRB** [comment]
да работает проверил

**Comment by foxdalas** [comment]
закрываем
