### ISSUE TITLE
Arcane Blast debuff fix 

### ISSUE THREAD

**Issue by gpadmin** [KiritoZ-Z/PhantomCore#23]
Compile error

**Comment by Viste** [comment]
what compile error?

**Comment by gpadmin** [comment]
2>....\src\game\Unit.cpp(10196) : error C2065: 'i' : undeclared identifier
2>....\src\game\Unit.cpp(10196) : error C2227: left of '->GetId' must point to class/struct/union/generic type
2>        type is ''unknown-type''
2>....\src\game\Unit.cpp(10197) : error C2044: illegal continue

У меня такая ошибка
