### ISSUE TITLE
Sanctified Scourgelord Т10 ДК

### ISSUE THREAD

**Issue by gpadmin** [KiritoZ-Z/PhantomCore#27]
При надевании 4 предметов сета должен кастоваться спел на владельца 70656, но пишет "invalid target" поэтому сет не работает.

**Comment by Viste** [comment]
ммм это вароподобный дк или локоподобный ?

**Comment by gpadmin** [comment]
Не совсем понял что ты имеешь ввиду, вот ссылка на предмет, см. сам.
http://www.wowhead.com/item=51314

**Comment by Viste** [comment]
этот я починил в последнем коммите, я думал ты про анхоли
