### ISSUE TITLE
Errors compile 71c07b22a1e1948d98a9

### ISSUE THREAD

**Issue by garyfisher** [KiritoZ-Z/PhantomCore#30]
Errors compile:

/home/phantom/src/game/Spell.cpp: In member function ‘SpellCastResult Spell::CheckCast(bool)’:

/home/phantom/src/game/Spell.cpp:5222: error: ‘class Unit’ has no member named ‘GetTypeID’

/home/phantom/src/game/Spell.cpp:5228: error: ‘class Unit’ has no member named ‘GetTypeID’

+

/home/phantom/src/game/SpellEffects.cpp: In member function ‘void Spell::EffectScriptEffect(uint32)’:

/home/phantom/src/game/SpellEffects.cpp:6110: error: break statement not within loop or switch

/home/phantom/src/game/SpellEffects.cpp: At global scope:

/home/phantom/src/game/SpellEffects.cpp:6112: error: expected unqualified-id before ‘case’

Linux Ubuntu 10.04 64bit

**Comment by Nagano-zz** [comment]
Errors compile release win 32:
http://paste2.org/p/848594
Sorri

**Comment by Viste** [comment]
PASTE2.ORG!!!!!!!!

**Comment by Bootz** [comment]
To fix the blood_queen_lanathel.cpp error, 
open the script "blood-queen_lanathel.cpp"
(..\src\scripts\northrend\icecrown_citadel)
and rename it to (blood_queen_lanathel.cpp).
i used "targetedmovementgenerator" and "homemovementgenerator" 
from tc repo, and made changes as necessary.
as for the spelleffect.cpp...i used a copy from 2 days back, 
and updated what was needed.
the other errors reported i don't seem to have.
 this was a very pain in the butt build error...

**Comment by Viste** [comment]
fixed
