### ISSUE TITLE
Characters rollbacks on login, Opcode error information.

### ISSUE THREAD

**Issue by AwkwardDev** [KiritoZ-Z/PhantomCore#33]
2010-05-24 17:11:37 ERROR: SESSION: received unexpected opcode CMSG_LOGOUT_CANCEL (0x004E) the player has not logged in yet

Honestly I have no clue what the hell this is and how to fix it xD. Anyone does have clue? I'm running high-rate, and its wreckless to see a level 40 member logged and then level 1 xD. Command .save does help, but a fix for it will be great! Also this is on the old Trinity, but no one have watched my report xD. If its my supidity, please correct me!

**Comment by Viste** [comment]
Okey we will fix it

**Comment by AwkwardDev** [comment]
Well, I just got the clue, its a wrong send information xD. Even Trinity has it, it will be great if you succeed in fixing this, I think my knowledge of programming is still low to fix this. And again Great work guys!

**Comment by AwkwardDev** [comment]
Any fix up yet? Its horrible xD.
