### ISSUE TITLE
Shaman - Благословение вечности

### ISSUE THREAD

**Issue by gpadmin** [KiritoZ-Z/PhantomCore#42]
Описание: Повышает вероятность критического эффекта ваших заклинаний на 2%. Повышает вероятность наложить эффект постепенного исцеления "Жизнь Земли" на союзников, чей запас здоровья не превышает 35%, на 40%.

Часть про "Жизнь Земли" не работает.

**Comment by Viste** [comment]
нет ссылки на вовхед иссуе идет лесом
