### ISSUE TITLE
Шаман - Огненный шок

### ISSUE THREAD

**Issue by gpadmin** [KiritoZ-Z/PhantomCore#44]
У данного скила, нет привязки к хасту кастера. У варлока подобное реализовано для спела "Жертвенный огонь"

**Comment by Viste** [comment]
нет ссылки на вовхед иссуе идет лесом

**Comment by SignFinder** [comment]
http://ru.wowhead.com/spell=49233 огненный шок
http://ru.wowhead.com/spell=47811 жертвенный огонь
