### ISSUE TITLE
Вскипание крови

### ISSUE THREAD

**Issue by gpadmin** [KiritoZ-Z/PhantomCore#49]
Кровь всех противников в радиусе 10 м вскипает, нанося им 180 - 220 ед. урона от темной магии. Цели, пораженные "Ознобом" или "Кровавой чумой", получают дополнительный урон.

привязки к болезням нет и почему то прокает спел 45903 по крайней мере у меня.

**Comment by Viste** [comment]
нет ссылки на вовхед иссуе идет лесом
