### ISSUE TITLE
Нечестивая порча

### ISSUE THREAD

**Issue by gpadmin** [KiritoZ-Z/PhantomCore#50]
3.3.3 Нечестивая порча: в дополнение к прежнему эффекту, теперь этот талант не позволяет развеять наложенные на цель, пораженную нечестивой порчей, болезни.

т.е. если на цели болезни, то их нельзя диспелить, в данный момент диспелятся как раньше.

**Comment by Viste** [comment]
нет ссылки на вовхед иссуе идет лесом
