### ISSUE TITLE
Mobs running :D.

### ISSUE THREAD

**Issue by AwkwardDev** [KiritoZ-Z/PhantomCore#53]
Once you get killed or you loose the agro of the mobs, any mobs ingame the mob just run on a random place ... after 2 mins its respawning on the place it should be. This is funny and not so bad, bug still its a bug.

**Comment by AwkwardDev** [comment]
http://pastebin.com/KnJ92fkb - because of this compile warning the mobs are fleeing on a random once loosed agro.

**Comment by diller** [comment]
нетолько мобы и босы убегают(или проваливаются в тексты), убегают также все петы(Локов, хантов, Дк и тд)  и все спутники =/

**Comment by salarik** [comment]
ммапы используйте чтоб не убегали. уже и Downloads*ах вам их выложили. Все равно толдычите об одном и том же.

**Comment by diller** [comment]
и как этого зверя на линукс воткнуть? можно гайдик если несложно

**Comment by AwkwardDev** [comment]
Well, I have fixed it on my own. I don't write russian, but I do speak and understand it :D.

**Comment by salarik** [comment]
http://paste2.org/p/850662 поможет. Больше нифига не надо для извлечения.

**Comment by diller** [comment]
и как это работает? что должно лежать в каталоге и как распаковать?
