### ISSUE TITLE
Нельзя-сесть на маунта, рес у спиритов.

### ISSUE THREAD

**Issue by Blocker-xx** [KiritoZ-Z/PhantomCore#54]
Последняя ревизия, творится непонятно что, нельзя сесть на маунтов, рес тоже неробит, это то что я успел посмотреть за 5 минут-пришлось откатить,  ибо ставил сразу на лайв

**Comment by nemmez** [comment]
Spell.cpp:  
                    if (duration <= 0)
                    {
                        m_spellAura->Remove();
                        return SPELL_MISS_IMMUNE;
                    }
замените на 
                    if (duration == 0)
                    {
                        m_spellAura->Remove();
                        return SPELL_MISS_IMMUNE;
                    }
