### ISSUE TITLE
No mout or spell aura can be runned.

### ISSUE THREAD

**Issue by AwkwardDev** [KiritoZ-Z/PhantomCore#55]
As the title says, you can't mount or anything that is a spell aura. Thats extremely bad xD. Yet I have no fix for this issue.

**Comment by Null45** [comment]
When kitiro fix compile, he don`t understand me and fail all works

**Comment by AwkwardDev** [comment]
Saw it, perfectly fixed, I actually though about same, but yet I'm afraid from my low knowledge of C++.
