### ISSUE TITLE
OutdoorPvPWG.h - развесёлый файл

### ISSUE THREAD

**Issue by foxdalas** [KiritoZ-Z/PhantomCore#58]
Собственно откройте файл в mc или любом другом редакторе и увидите следующее
.#.d.e.f.i.n.e. .P.O.S._.X._.C.E.N.T.E.R. . . . . . . . . . . . . . . . .5.1.0.0.

=> компиляция на линуксе не возможна

**Comment by Sw2rT1** [comment]
Обнови исходники

**Comment by foxdalas** [comment]
это вы решили на основании фикса на компиляцию в линуксе ? =) Проблема осталась

**Comment by Sw2rT1** [comment]
http://a.imagehost.org/0183/1_113.png

**Comment by foxdalas** [comment]
http://j.imagehost.org/0061/phantom1.png
http://a.imagehost.org/0934/phantom2.png
угощайтесь, http://github.com/Kirito/PhantomCore/blob/577833202e9c04dcbd86759d41e270db10c2257c/src/game/OutdoorPvPWG.h смотрим сюда и о чудо, я прав =)

**Comment by Sw2rT1** [comment]
У меня кодировка не та почему то.. Вопросики там
