### ISSUE TITLE
Цлк Лорд ребард bugs

### ISSUE THREAD

**Issue by diller** [KiritoZ-Z/PhantomCore#61]
Босс кастует Холодное пламя неправильно, оно не должно бегать за игроками а должно стелится по земле тонким прямым потоком,исходить из самого боса и строго в прямом направлении стелится в рандомно выбранного игрока(если игрок сдвинется с места поток не меняет направления), а не появляться в рендомном месте + он его кастует очень часто, через 2 минуты боя с босом вся комната в находится в пламени, ну и соответственно вайп
спелы:
69146,
70823,
70824,
70825,
69138
- холодное пламя(http://ru.wowhead.com/npc=36672) остается как лужа и не исчезает кто зайдет в него сразу умрет =/ должно сразу исчезать дойдя до стены

**Comment by salarik** [comment]
подтверждаю.
