### ISSUE TITLE
Исследования алхимии и начертания

### ISSUE THREAD

**Issue by diller** [KiritoZ-Z/PhantomCore#66]
не работают спеллы
http://ru.wowhead.com/spell=61288 - Исследование малого начертания
http://ru.wowhead.com/spell=61177 - Исследование нордскольского начертания
http://ru.wowhead.com/spell=60893 - Исследование трав Нордскола
при исследовании ничего не происходит, не учатся новые рецепты

**Comment by Null45** [comment]
Ласт рева Стдб+ фантом. Всё учится

**Comment by crAwling** [comment]
Учится, но как раз не все :)
