### ISSUE TITLE
Arena preparation phase

### ISSUE THREAD

**Issue by ghost** [KiritoZ-Z/PhantomCore#67]
When you enter arena, you can see your enemies.
This worked back in 3.1.3

**Comment by Null45** [comment]
More information please

**Comment by ghost** [comment]
Okay

When you enter arena
Team 1 = phasing 2
Team 2 = phasing 3

When the arena starts = phasing 1

The problem we got atm is that both tean 1-2 gets in "phasing 2" so they can see eichother
