### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ghost** [KiritoZ-Z/PhantomCore#71]
8>....\src\game\Unit.cpp(663) : error C3861: 'GetWeaponAttackType': identifier not found
8>....\src\game\Unit.cpp(670) : error C2661: 'Player::CastItemCombatSpell' : no overloaded function takes 2 arguments

8>....\src\game\sc_boss_spell_worker.cpp(602) : error C2065: '_list' : undeclared identifier
8>....\src\game\sc_boss_spell_worker.cpp(602) : error C2065: '_list' : undeclared identifier
8>....\src\game\sc_boss_spell_worker.cpp(602) : error C2070: ''unknown-type'': illegal sizeof operand
8>....\src\game\sc_boss_spell_worker.cpp(616) : error C2065: '_list' : undeclared identifier
8>....\src\game\sc_boss_spell_worker.cpp(623) : error C2065: '_list' : undeclared identifier

**Comment by foxdalas** [comment]
исправлено
