### ISSUE TITLE
Not compile

### ISSUE THREAD

**Issue by SignFinder** [KiritoZ-Z/PhantomCore#73]
Начал собирать сегодняшную ревизию и получил вот что
[ 93%] Building CXX object src/shared/vmap/CMakeFiles/vmaps.dir/VMapManager2.cpp.o
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/ext/hashtable.h: In member function ‘size_t __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::_M_bkt_num_key(const _Key&, size_t) const [with _Val = std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel>, _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _HashFcn = __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _ExtractKey = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel> >, _EqualKey = std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocatorVMAP::ManagedModel]’:
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/ext/hashtable.h:588:   instantiated from ‘size_t __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::_M_bkt_num_key(const _Key&) const [with _Val = std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel>, _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _HashFcn = __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _ExtractKey = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel> >, _EqualKey = std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocatorVMAP::ManagedModel]’
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/ext/hashtable.h:592:   instantiated from ‘size_t __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::_M_bkt_num(const _Val&) const [with _Val = std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel>, _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _HashFcn = __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _ExtractKey = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel> >, _EqualKey = std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocatorVMAP::ManagedModel]’
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/ext/hashtable.h:646:   instantiated from ‘__gnu_cxx::_Hashtable_iterator<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>& __gnu_cxx::_Hashtable_iterator<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::operator++() [with _Val = std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel>, _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _HashFcn = __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _ExtractKey = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel> >, _EqualKey = std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocatorVMAP::ManagedModel]’
/home/trinity/repos/PhantomCore/src/shared/vmap/VMapManager2.cpp:48:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/ext/hashtable.h:596: ошибка: не найден метод для преобразования в ‘(const __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >) (const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)’
make[2]: **\* [src/shared/vmap/CMakeFiles/vmaps.dir/VMapManager2.cpp.o] Ошибка 1
make[1]: **\* [src/shared/vmap/CMakeFiles/vmaps.dir/all] Ошибка 2

**Comment by xeptor** [comment]
Can you upgrade your gcc 4.1.3?

**Comment by Eulogy** [comment]
Same problem here, my version is RHEL 5.5 and i have gcc 4.1.2 , No updates available. 

:/

**Comment by SignFinder** [comment]
Centos 5.5 have gcc44 packet. And use -DCENTOS=1 flag witch cmake

**Comment by SignFinder** [comment]
yum install gcc-c++44 and use -DCMAKE_C_COMPILER=/usr/bin/gcc44 -DCMAKE_CXX_COMPILER=/usr/bin/g++44 flags with cmake in Centos 5.5

**Comment by Eulogy** [comment]
not allow me to use these flags, but modify the file and add the lines CMakeCache.txt you listed, thank you very much.

**Comment by burnham** [comment]
Same problem for me in linux ububtu server:

[  7%] Building CXX object src/shared/Config/CMakeFiles/phantomconfig.dir/dotconfpp/mempool.cpp.o
[  7%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/prompt.cpp.o
/usr/include/c++/4.2/ext/hashtable.h: In member function 'size_t __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::_M_bkt_num_key(const _Key&, size_t) const [with _Val = std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel>, _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _HashFcn = __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _ExtractKey = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel> >, _EqualKey = std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocatorVMAP::ManagedModel]':
/usr/include/c++/4.2/ext/hashtable.h:587:   instantiated from 'size_t __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::_M_bkt_num_key(const _Key&) const [with _Val = std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel>, _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _HashFcn = __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _ExtractKey = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel> >, _EqualKey = std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocatorVMAP::ManagedModel]'
/usr/include/c++/4.2/ext/hashtable.h:591:   instantiated from 'size_t __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::_M_bkt_num(const _Val&) const [with _Val = std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel>, _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _HashFcn = __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _ExtractKey = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel> >, _EqualKey = std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocatorVMAP::ManagedModel]'
/usr/include/c++/4.2/ext/hashtable.h:645:   instantiated from '__gnu_cxx::_Hashtable_iterator<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>& __gnu_cxx::_Hashtable_iterator<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::operator++() [with _Val = std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel>, _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _HashFcn = __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _ExtractKey = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel> >, _EqualKey = std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocatorVMAP::ManagedModel]'
/home/trinity/PhantomCore/src/shared/vmap/VMapManager2.cpp:48:   instantiated from here
/usr/include/c++/4.2/ext/hashtable.h:595: error: no hay coincidencia para la llamada a '(const __gnu_cxx::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >) (const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
[  7%] make[2]: **\* [src/shared/vmap/CMakeFiles/vmaps.dir/VMapManager2.cpp.o] Error 1
make[2]: **\* Se espera a que terminen otras tareas....
Building CXX object src/shared/Config/CMakeFiles/phantomconfig.dir/Config.cpp.o
Scanning dependencies of target phantomdatabase
[  8%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/stringutils.cpp.o

Thanks for help and recomendations.
