### ISSUE TITLE
cant compile - windows

### ISSUE THREAD

**Issue by ghost** [KiritoZ-Z/PhantomCore#74]
8>....\src\game\SpellAuraEffects.cpp(1878) : error C2360: initialization of 'pvpWG' is skipped by 'case' label
8>        ....\src\game\SpellAuraEffects.cpp(1869) : see declaration of 'pvpWG'
8>....\src\game\SpellAuraEffects.cpp(1885) : error C2360: initialization of 'pvpWG' is skipped by 'case' label
8>        ....\src\game\SpellAuraEffects.cpp(1869) : see declaration of 'pvpWG'
8>....\src\game\SpellAuraEffects.cpp(1889) : error C2360: initialization of 'pvpWG' is skipped by 'case' label
8>        ....\src\game\SpellAuraEffects.cpp(1869) : see declaration of 'pvpWG'
8>....\src\game\SpellAuraEffects.cpp(1897) : error C2360: initialization of 'pvpWG' is skipped by 'case' label
8>        ....\src\game\SpellAuraEffects.cpp(1869) : see declaration of 'pvpWG'

8>....\src\game\BattleGroundMgr.cpp(241) : error C2065: 'LANG_BG_QUEUE_ANNOUNCE_SELF' : undeclared identifier
8>....\src\game\BattleGroundMgr.cpp(247) : error C2065: 'LANG_BG_QUEUE_ANNOUNCE_WORLD' : undeclared identifier
8>BattleGroundHandler.cpp
8>....\src\game\BattleGroundHandler.cpp(62) : error C2065: 'LANG_YOUR_BG_LEVEL_REQ_ERROR' : undeclared identifier

**Comment by Null45** [comment]
Fixed now

**Comment by ghost** [comment]
thx
