### ISSUE TITLE
Warnings при компиляции 

### ISSUE THREAD

**Issue by eugene-matvejev** [KiritoZ-Z/PhantomCore#76]
http://freetexthost.com/uvxwzfw00w
Тут захостил, уж слишком много их

**Comment by Misimouse** [comment]
same on the last commit today 02.08.10

this core is only for 32 bits (win) or maybe only for Linux 64? I cant' compile on win x64, any help please.

**Comment by Misimouse** [comment]
Ups sorry I'm compiling wit Visual Studio 2.008
