### ISSUE TITLE
Compile errors report log.

### ISSUE THREAD

**Issue by AwkwardDev** [KiritoZ-Z/PhantomCore#8]
10>....\src\phantomcore\Master.cpp(31) : fatal error C1083: Cannot open include file: 'SignalHandler.h': No such file or directory

8>c1xx : fatal error C1083: Cannot open source file: '....\src\scripts\northrend\crusaders_coliseum\trial_of_the_crusader\Twin_Valkyr.cpp': No such file or directory
8>trial_of_the_crussader.cpp
8>c1xx : fatal error C1083: Cannot open source file: '....\src\scripts\northrend\crusaders_coliseum\trial_of_the_crusader\trial_of_the_crussader.cpp': No such file or directory
8>instance_trial_of_the_crussader.cpp
8>boss_northrend_beasts.cpp
8>c1xx : fatal error C1083: Cannot open source file: '....\src\scripts\northrend\crusaders_coliseum\trial_of_the_crusader\instance_trial_of_the_crussader.cpp': No such file or directory
8>boss_lord_jaraxxus.cpp
8>c1xx : fatal error C1083: Cannot open source file: '....\src\scripts\northrend\crusaders_coliseum\trial_of_the_crusader\boss_northrend_beasts.cpp': No such file or directory
8>Anubarak.cpp
8>c1xx : fatal error C1083: Cannot open source file: '....\src\scripts\northrend\crusaders_coliseum\trial_of_the_crusader\boss_lord_jaraxxus.cpp': No such file or directory
8>oculus.cpp
8>c1xx : fatal error C1083: Cannot open source file: '....\src\scripts\northrend\crusaders_coliseum\trial_of_the_crusader\Anubarak.cpp': No such file or directory
Thats the report log I got with all the errors. Here is a part of the 108 warnings I got, they all are same!

8>c:\documents and settings\administrator\desktop\phantom core 337 (3.3.3a)\src\framework\utilities\linkedlist.h(97) : warning C4715: 'LinkedListHead::isEmpty' : not all control paths return a value

I have no time to try to fix it on my own, thats why I'm reporting it. Good luck with fixing this! And great core!

**Comment by Viste** [comment]
paste it on paste2.org
