### ISSUE TITLE
фикс на нитроускорители(В Инжинерии) на БГ(Око бури, Ущелье песни войны)

### ISSUE THREAD

**Issue by cemak** [KiritoZ-Z/PhantomCore#83]
Баг заключался в том, что когда юзаешь этот эффект с флагом, то флаг сбрасывался..
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment
Ущелье песни войны 

( 54861,-23335, 0, 'Drop Flag on Nitro Boost WSG'),

( 54861,-23333, 0, 'Drop Flag on Nitro Boost WSG'),

( 55004,-23335, 0, 'Drop Flag on Nitro Boost WSG'),

( 55004,-23333, 0, 'Drop Flag on Nitro Boost WSG'),

Око бури

( 54861,-34976, 0, 'Drop Flag on Nitro Boost EOS'),

( 55004,-34976, 0, 'Drop Flag on Nitro Boost EOS');

**Comment by SignFinder** [comment]
fixed in commit 5d468c80cbf709747153
