### ISSUE TITLE
Не компилируется после коммита 6a433abcf1c6d046ea3206db775cf70453bb6649

### ISSUE THREAD

**Issue by ilyazub** [KiritoZ-Z/PhantomCore#89]
http://github.com/Kirito/PhantomCore/commit/6a433abcf1c6d046ea3206db775cf70453bb6649

/home/physx/phantomcore/src/server/game/Entities/Pet/Pet.cpp: In member function 'bool Guardian::InitStatsForLevel(uint8)':
/home/physx/phantomcore/src/server/game/Entities/Pet/Pet.cpp:983: error: no matching function for call to 'Unit::HasAuraEffect(int)'
/home/physx/phantomcore/src/server/game/Entities/Unit/Unit.h:1612: note: candidates are: bool Unit::HasAuraEffect(uint32, uint8, uint64) const
/home/physx/phantomcore/src/server/game/Entities/Pet/Pet.cpp:988: error: 'bonus_dmg' was not declared in this scope

**Comment by SignFinder** [comment]
fixed
