### ISSUE TITLE
Ошибка конфигурации

### ISSUE THREAD

**Issue by Pilop** [KiritoZ-Z/PhantomCore#9]
wow# cmake ../ -DPREFIX=/opt/compile/binrelax5/ -DCMAKE_C_FLAGS="-O2" -DCMAKE_CXX_FLAGS="-O2" -DDO_DEBUG=0 -DDO_SCRIPTS=true -DCMAKE_DFD_SETSIZE=4096 -DLARGE_CELL=0 -DSHORT_SLEEP=1 -DCMAKE_C_FLAGS="-march=prescott -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -pipe -pipe -msse3 -fomit-frame-pointer -ffast-math -fno-strength-reduce -fno-strict-aliasing -frename-registers"
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:10 (include):
  include could not find load file:

```
cmake/PCH.cmake
```
- PhantomCore revision:
- Will install to: /opt/compile/binrelax5/
- With config dir at: /opt/compile/binrelax5//etc
- Libs install dir at: /opt/compile/binrelax5//lib
- With MySQL
  -- Using mysql-config: /usr/local/bin/mysql_config
  -- Found MySQL: /usr/local/include/mysql, /usr/local/lib/mysql/libmysqlclient_r.so;/usr/lib/libz.so;/usr/lib/libcrypt.so;/usr/lib/libm.so
- With Phantom Scripts
  -- Miscellaneus options:
- With CLI
- Without RA
- Building with readline
  -- Found Readline library: /usr/lib/libreadline.so
  -- Include dir is: /usr/include
  -- Found ACE library: /usr/local/lib/libACE.so
  -- Include dir is: /usr/local/include
  CMake Error at src/game/CMakeLists.txt:357 (ADD_PRECOMPILED_HEADER):
  Unknown CMake command "ADD_PRECOMPILED_HEADER".

-- Configuring incomplete, errors occurred!

**Comment by Viste** [comment]
у меня все ок

**Comment by Pilop** [comment]
не хватает файлов для Freebsd:
/cmake/PCH.cmake  
/src/game/pchlinux.cpp  
/src/game/pchlinux.h

**Comment by Viste** [comment]
в геиме даже на офф репо нет таких файлов

**Comment by Pilop** [comment]
http://code.google.com/p/trinitycore/source/browse/src/game/pchlinux.cpp?spec=svndbc7e6f33c7c9e7ded998aa9be896734a97cbbd3&r=89faa374e9f2d231b5108fefcc5ce91efd81f529

И вот
http://code.google.com/p/trinitycore/source/browse/src/game/pchlinux.h?spec=svndbc7e6f33c7c9e7ded998aa9be896734a97cbbd3&r=89faa374e9f2d231b5108fefcc5ce91efd81f529
