### ISSUE TITLE
[LINUX] Compile broken

### ISSUE THREAD

**Issue by GuguRD** [KiritoZ-Z/PhantomCore#91]
Linux compile is still broken... hpe this helps.

[ 28%] Building CXX object src/server/game/CMakeFiles/game.dir/Entities/Pet/Pet.cpp.o
/home/repos/PhantomCore/src/server/game/Entities/Pet/Pet.cpp: In member function âbool Guardian::InitStatsForLevel(uint8)â:
/home/repos/PhantomCore/src/server/game/Entities/Pet/Pet.cpp:983: error: no matching function for call to âUnit::HasAuraEffect(int)â
/home/repos/PhantomCore/src/server/game/Entities/Unit/Unit.h:1612: note: candidates are: bool Unit::HasAuraEffect(uint32, uint8, uint64) const
/home/repos/PhantomCore/src/server/game/Entities/Pet/Pet.cpp:988: error: âbonus_dmgâ was not declared in this scope
[ 28%] Building CXX object src/server/game/CMakeFiles/game.dir/Entities/Player/Player.cpp.o
[ 28%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/ZulGurub/boss_jindo.cpp.o
make[2]: **\* [src/server/game/CMakeFiles/game.dir/Entities/Pet/Pet.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....

---

Thanks in advance.

**Comment by SignFinder** [comment]
fixed
