### ISSUE TITLE
Linux Compile Error

### ISSUE THREAD

**Issue by GuguRD** [KiritoZ-Z/PhantomCore#97]
Looks like someone forgot to update cmake files hehe..

[ 75%] make[2]: **\* No rule to make target `../src/server/scripts/Northrend/CrusadersColiseum/trial_of_the_crusader/boss_champions.cpp', needed by`src/server/scripts/CMakeFiles/scripts.dir/Northrend/CrusadersColiseum/trial_of_the_crusader/boss_champions.cpp.o'.  Stop.
make[2]: **\* Waiting for unfinished jobs....
Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Northrend/Nexus/Oculus/boss_drakos.cpp.o
make[1]: **\* [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: **\* [all] Error 2

**Comment by SignFinder** [comment]
last rev compile normal

**Comment by GuguRD** [comment]
SignFinder maybe you have to merge your repo because it is still with the same problem, I have just cloned the repo again.

[ 75%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Northrend/Nexus/Oculus/boss_eregos.cpp.o
[ 75%] make[2]: **\* No rule to make target `../src/server/scripts/Northrend/CrusadersColiseum/trial_of_the_crusader/boss_champions.cpp', needed by`src/server/scripts/CMakeFiles/scripts.dir/Northrend/CrusadersColiseum/trial_of_the_crusader/boss_champions.cpp.o'.  Stop.
make[2]: **\* Waiting for unfinished jobs....
Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Northrend/Nexus/Oculus/boss_drakos.cpp.o

**Comment by GuguRD** [comment]
Slap my fae please... completely my mistake! =(
